var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "yyyy年 L d日",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d日",
            "sun": "周日",
            "mon": "周一",
            "tue": "周二",
            "wed": "周三",
            "thu": "周四",
            "fri": "周五",
            "sat": "周六",
            "jan": "1月",
            "feb": "2月",
            "mar": "3月",
            "apr": "4月",
            "may": "5月",
            "jun": "6月",
            "jul": "7月",
            "aug": "8月",
            "sep": "9月",
            "oct": "10月",
            "nov": "11月",
            "dec": "12月"
        },
		"no_implemented": "没有实现",
        "to_date_view": "点击转到该日期的日视图",
        "i_undefined": "未设置",
        "allday_event": "全天日程",
        "repeat_event": "跨天日程",
        "time": "时  间",
        "event": "事  件",
        "location": "地  点",
        "participant": "参与人",
        "get_data_exception": "获取数据发生异常",
        "new_event": "新日程",
        "confirm_delete_event": "确定删除该日程吗？",
        "confrim_delete_event_or_all": "删除此序列还是单个事件？\r\n点击[确定]删除事件,点击[取消]删除序列",
        "data_format_error": "数据格式错误！",
        "invalid_title": "日程标题不能为空且不能包含符号($<>)",
        "view_no_ready": "视图未准备就绪",
        "example": "例如：有个办公会议",
        "content": "内 容",
        "create_event": "创建日程",
        "update_detail": "修改日程详细信息",
        "click_to_detail": "点击查看详细",
        "i_delete": "删除",
        "day_plural": "天",
        "others": "另外",
        "item": "个"
    }
});
